hyperskill_project:
  id: 193
  ide_files: https://cogniterra.org/media/attachments/lesson/25639/additional_files.json
  is_template_based: false
  use_ide: true
update_date: "Wed, 01 May 2024 04:59:43 UTC"
stages:
  - id: 962
    step: 13999
    is_completed: true
  - id: 963
    step: 14000
    is_completed: true
  - id: 964
    step: 14001
    is_completed: true
topics:
  0:
    - title: Block-level elements
      theory_id: 7271
    - title: Inline elements
      theory_id: 7518
    - title: What is CSS
      theory_id: 7678
    - title: HTML attributes id and class
      theory_id: 7527
    - title: Connecting CSS to HTML
      theory_id: 7418
    - title: Basic syntax
      theory_id: 7722
    - title: CSS Selectors
      theory_id: 7738
    - title: Relative units
      theory_id: 10671
    - title: Absolute units
      theory_id: 10605
    - title: Introduction to Flexbox
      theory_id: 11760
    - title: Orientation and Display order
      theory_id: 11768
    - title: DOM
      theory_id: 8635
    - title: HTML basics
      theory_id: 6434
    - title: Tags and Attributes
      theory_id: 7536
    - title: HTML page structure
      theory_id: 6491
    - title: Comments
      theory_id: 7502
    - title: Position
      theory_id: 11581
    - title: Float
      theory_id: 12697
    - title: Clear
      theory_id: 12705
    - title: Margin and Padding
      theory_id: 26903
    - title: Width and Height
      theory_id: 8325
  1:
    - title: Comments
      theory_id: 8170
    - title: Connecting JavaScript to HTML
      theory_id: 7510
    - title: Introduction to JavaScript
      theory_id: 8016
    - title: Writing first program
      theory_id: 8154
    - title: Multi-line programs
      theory_id: 8162
    - title: Declaring variables
      theory_id: 8186
    - title: Strings and numbers
      theory_id: 8194
    - title: Arithmetic operators
      theory_id: 8372
    - title: Functions
      theory_id: 8388
    - title: JSON
      theory_id: 6854
    - title: Introduction to Objects
      theory_id: 8588
    - title: Intro to DOM events
      theory_id: 10857
    - title: DOM methods
      theory_id: 8662
    - title: The "addEventListener" method
      theory_id: 8723
    - title: Introduction to String
      theory_id: 17747
    - title: String transforming
      theory_id: 17779
  2:
    - title: Starting with git
      theory_id: 10894
